apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "three-tier-app.fullname" . }}-frontend-nginx
  namespace: {{ .Values.namespace.name }}
  labels:
    app: frontend
    {{- include "three-tier-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://{{ include "three-tier-app.backendHost" . }}:{{ .Values.frontend.backendPort }}/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
