apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "three-tier-app.fullname" . }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    {{- include "three-tier-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.targetPort }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "three-tier-app.fullname" . }}-postgres
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "three-tier-app.fullname" . }}-postgres
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "three-tier-app.fullname" . }}-postgres
                  key: DB_PASSWORD
          {{- if .Values.postgres.probes.enabled }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: {{ .Values.postgres.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.readiness.periodSeconds }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: {{ .Values.postgres.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.liveness.periodSeconds }}
          {{- end }}
          {{- if .Values.postgres.storage.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          {{- end }}
      {{- if .Values.postgres.storage.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "three-tier-app.fullname" . }}-postgres-data
      {{- end }}
